;-----------------------------------------------------------------------------------
; 
; Data: History
; 
;-----------------------------------------------------------------------------------

    module Cat

table:
    dw p1,p2,p3,p4,p5,p6,p7,p8,p9,p10
    dw p11,p12,p13,p14,p15,p16,p17,p18,p19,p20
    dw p21,p22,p23,p24,p25,p26,p27,p28,p29,p30
    dw p31,p32,p33,p34,p35,p36,p37,p38,p39,p40
    dw p41,p42,p43,p44,p45,p46,p47,p48,p49,p50

p1: db "NELSON'S ENGAGEMENTS",0
    db "BATTLE OF\nTHE NILE",0
    db "BATTLE OF\nTRAFALGAR",0
    db "BATTLE OF\nSANTA CRUZ\nDE TENERIFE",0

p2: db "FAMOUS BATTLES",0
    db "BATTLE OF\nHASTINGS",0
    db "BATTLE OF\nAGINCOURT",0
    db "BATTLE OF\nBOSWORTH\nFIELD",0

p3: db "US CIVIL WAR",0
    db "BATTLE OF\nSHILOH",0   
    db "BATTLE OF\nFORT SUMTER",0
    db "FIRST BATTLE\nOF BULL RUN",0

p4: db "WWII BATTLES",0
    db "BATTLE OF\nBRITAIN",0
    db "OPERATION\nBARBAROSSA",0
    db "OPERATION\nMARKET\nGARDEN",0

p5: db "WWII BATTLES",0
    db "BATTLE OF\nTHE BULGE",0
    db "NORMANDY\nINVASION",0
    db "ALLIED\nINVASION\nOF SICILY",0

p6: db "WWII BATTLES",0
    db "BATTLE OF\nMIDWAY",0
    db "ATTACK ON\nPEARL HARBOR",0
    db "GUADALCANAL\nCAMPAIGN",0

p7: db "WWII BATTLES",0
    db "INVASION\nOF POLAND",0
    db "SIEGE OF\nLENINGRAD",0
    db "BATTLE OF\nMONTE\nCASSINO",0

p8: db "WWI BATTLES",0
    db "BATTLE OF\nTHE SOMME",0
    db "FIRST BATTLE\nOF YPRES",0
    db "GALLIPOLI\nCAMPAIGN",0

p9: db "WWI BATTLES",0
    db "BATTLE OF\nJUTLAND",0
    db "SPRING\nOFFENSIVE",0
    db "SECOND\nBATTLE OF\nTHE MARNE",0

p10: db "CRIMEAN WAR",0
    db "BATTLE OF\nSINOP",0
    db "BATTLE OF\nBALACLAVA",0
    db "SIEGE OF\nSEVASTOPOL",0

p11: db "WAR OF 1812",0
    db "BATTLE OF\nLAKE ERIE",0
    db "BATTLE OF\nHORSESHOE\nBEND",0
    db "BURNING OF\nWASHINGTON",0

p12: db "AMERICAN WAR OF INDEPENDENCE",0
    db "SIEGE OF\nYORKTOWN",0
    db "BATTLE OF\nBUNKER HILL",0
    db "BATTLE OF\nBRANDYWINE",0

p13: db "ROMAN BATTLES",0
    db "BATTLE OF\nACTIUM",0
    db "BATTLE OF\nWATLING\nSTREET",0
    db "BATTLE OF\nTEUTOBURG\nFOREST",0

p14: db "WHAT HAVE THE ROMANS...",0
    db "AQUEDUCTS",0
    db "HYPOCAUSTS",0
    db "THE ROMAN\nALPHABET",0

p15: db "WHAT HAVE THE ROMANS...",0
    db "CONCRETE",0
    db "SEWERS AND\nSANITATION",0
    db "PUBLIC BATHS\nAND HYGIENE",0

p16: db "WWII BOMBERS",0
    db "AVRO\nLANCASTER",0
    db "VICKERS\nWELLINGTON",0
    db "HANDLEY PAGE\nHALIFAX",0

p17: db "WWII FIGHTER PLANES",0
    db "SUPERMARINE\nSPITFIRE",0
    db "HAWKER\nHURRICANE",0
    db "DE HAVILLAND\nMOSQUITO",0

p18: db "ROMAN EMPERORS",0
    db "AUGUSTUS",0
    db "MARCUS\nAURELIUS",0
    db "CONSTANTINE\nTHE GREAT",0

p19: db "ROMAN ARCHITECTURE",0
    db "HADRIANS\nWALL",0
    db "PONT DU\nGARD",0
    db "CIRCUS\nMAXIMUS",0

p20: db "ROMAN ARCHITECTURE",0
    db "PANTHEON",0
    db "COLOSSEUM",0
    db "BATHS OF\nCARACALLA",0

p21: db "ALEXANDER THE GREAT",0
    db "BATTLE OF\nISSUS",0
    db "SIEGE OF\nTYRE",0
    db "BATTLE OF\nTHE PERSIAN\nGATES",0

p22: db "ENGLISH CIVIL WAR",0
    db "BATTLE OF\nEDGEHILL",0
    db "BATTLE OF\nNANTWICH",0
    db "BATTLE OF\nMARSTON MOOR",0

p23: db "FAMOUS WARS",0
    db "WAR OF\nTHE ROSES",0
    db "HUNDRED\nYEARS WAR",0
    db "NAPOLEONIC\nWARS",0

p24: db "FAMOUS WARS",0
    db "CRUSADES",0
    db "AMERICAN\nCIVIL WAR",0
    db "FRANCO\nPRUSSIAN\nWAR",0

p25: db "GREAT HISTORICAL EVENTS",0
    db "INVENTION OF\nTHE WHEEL",0
    db "THE\nRENAISSANCE",0
    db "THE\nINDUSTRIAL\nREVOLUTION",0

p26: db "GREAT HISTORICAL EVENTS",0
    db "THE BIRTH\nOF WRITING",0
    db "FALL OF THE\nROMAN EMPIRE",0
    db "BRITISH\nAGRICULTURAL\nREVOLUTION",0

p27: db "EMPIRES",0
    db "EGYPTIAN\nEMPIRE",0
    db "BABYLONIAN\nEMPIRE",0
    db "MACEDONIAN\nEMPIRE",0

p28: db "EMPIRES",0
    db "HAN DYNASTY",0
    db "GUPTA EMPIRE",0
    db "UMAYYAD\nCALIPHATE",0

p29: db "EMPIRES",0
    db "JAPANESE\nEMPIRE",0
    db "FRENCH\nCOLONIAL\nEMPIRE",0
    db "AUSTRO\nHUNGARIAN\nEMPIRE",0

p30: db "EMPIRES",0
    db "TANG DYNASTY",0
    db "BYZANTINE\nEMPIRE",0
    db "ABBASID\nCALIPHATE",0

p31: db "MEDIAEVAL TRIAL AND PUNISHMENTS",0
    db "DUCKING STOOL",0
    db "BURNING AT\nTHE STAKE",0
    db "HUNG DRAWN\nAND QUARTERED",0

p32: db "FRENCH TRIAL AND PUNISHMENTS",0
    db "GUILLOTINE",0
    db "OUBLIETTE",0
    db "PEINE FORTE\nET DURE",0

p33: db "FAMOUS PLANES",0
    db "ENOLA GAY",0
    db "SPIRIT OF\nST LOUIS",0
    db "MEMPHIS\nBELLE",0

p34: db "PLOTS",0
    db "THE\nGUNPOWDER\nPLOT",0
    db "THE\nBABINGTON\nPLOT",0
    db "THE CATO\nSTREET\nCONSPIRACY",0

p35: db "FAMOUS DATES",0
    db "IDES OF\nMARCH",0
    db "BLACK\nTUESDAY",0
    db "BASTILLE DAY",0

p36: db "ASSASSINS",0
    db "LEE HARVEY\nOSWALD",0
    db "JOHN WILKES\nBOOTH",0
    db "CHARLOTTE\nCORDAY",0

p37: db "REVOLUTIONARIES",0
    db "CHE GUEVARA",0
    db "VLADIMIR\nLENIN",0
    db "MAXIMILIEN\nROBESPIERRE",0

p38: db "REVOLUTIONARIES",0
    db "HO CHI MINH",0
    db "SIMON\nBOLIVAR",0
    db "TOUSSAINT\nLOUVERTURE",0

p39: db "FAMOUS BOATS",0
    db "BISMARCK",0
    db "HMS ENDEAVOUR",0
    db "MARIE\nCELESTE",0

p40: db "FAMOUS BOATS",0
    db "MAYFLOWER",0
    db "SANTA MARIA",0
    db "USS\nCONSTITUTION",0

p41: db "FAMOUS BOATS",0
    db "KON TIKI",0
    db "HMS BEAGLE",0
    db "HMS\nCHALLENGER",0

p42: db "ARMOUR",0
    db "GAUNTLETS",0
    db "CUIRASS",0
    db "REREBRACE",0

p43: db "ARMOUR",0
    db "GREAVES",0
    db "SABATONS",0
    db "PAULDRONS",0

p44: db "SWORDS",0
    db "GLADIUS",0
    db "SCIMITAR",0
    db "ULFBERHT",0

p45: db "MEDIAEVAL INVENTIONS",0
    db "SEED DRILL",0
    db "WINDMILL",0
    db "HEAVY PLOUGH",0

p46: db "ANCIENT CHINESE INVENTIONS",0
    db "BLAST\nFURNACE",0
    db "MECHANICAL\nCLOCK",0
    db "GUNPOWDER AND\nFIREWORKS",0

p47: db "ANCIENT CHINESE INVENTIONS",0
    db "COMPASS",0
    db "WHEELBARROW",0
    db "SEISMOSCOPE",0

p48: db "ANCIENT CHINESE INVENTIONS",0
    db "PAPER MONEY",0
    db "PORCELAIN",0
    db "ACUPUNCTURE",0

p49: db "INDUSTRIAL REVOLUTION TECH",0
    db "SPINNING\nJENNY",0
    db "FLYING\nSHUTTLE",0
    db "STEPHENSONS\nROCKET",0

p50: db "INDUSTRIAL REVOLUTION TECH",0
    db "STEAM ENGINE",0
    db "BESSEMER\nPROCESS",0
    db "RUBBER\nVULCANIZATION",0

    endmodule