INK                     EQU $10
PAPER                   EQU $11
FLASH                   EQU $12
BRIGHT                  EQU $13
INVERSE                 EQU $14
OVER                    EQU $15
AT                      EQU $16
TAB                     EQU $17
CR                      EQU $0C
